apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: common-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      serviceAccountName: common-api@ureuzy-common.iam.gserviceaccount.com
      containers:
      - image: common-api-image
        env:
        - name: PORT
          value: "8080"
        - name: BUCKET_NAME
          value: "ureuzy-family-photos"
        - name: PROJECT_ID
          value: "ureuzy-common"
        - name: FIREBASE_PROJECT_ID
          value: "ureuzy"
