apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: ai-web-summarizer
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - image: ai-web-summarizer-image
            env:
            - name: CHANNEL
              value: "#news"
            - name: TARGET_URLS
              value: "https://aws.amazon.com/jp/about-aws/whats-new/recent/feed/,https://docs.cloud.google.com/release-notes,https://lwkd.info/feed.xml" # プレースホルダー、実際にはカンマ区切りで指定可能
            - name: PROJECT_ID
              value: "ureuzy-ai"
            - name: LOCATION
              value: "global"
            - name: GEMINI_MODEL
              value: "gemini-3-flash-preview"
            - name: SLACK_WEBHOOK
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: slack-webhook
          serviceAccountName: ai-web-summarizer@ureuzy-common.iam.gserviceaccount.com # 既存のSAを流用（Vertex AI権限が必要）
